name: Debug

on: push

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - run: echo ref_name = ${{github.ref_name}}
      - run: echo base_ref = ${{github.base_ref}}
      - run: >-
          echo base_ref.moose-version = 
          ${{ vars.BRANCHES_CONFIGURATION 
          && fromJSON(vars.BRANCHES_CONFIGURATION)[github.base_ref]
          && fromJSON(vars.BRANCHES_CONFIGURATION)[github.base_ref].moose-version }}
      - run: >-
          echo ref_name.moose-version = 
          ${{ vars.BRANCHES_CONFIGURATION 
          || fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name] 
          && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name].moose-version }}
      - run: >-
          echo Full = 
          ${{ vars.BRANCHES_CONFIGURATION 
          && fromJSON(vars.BRANCHES_CONFIGURATION)[github.base_ref]
          && fromJSON(vars.BRANCHES_CONFIGURATION)[github.base_ref].moose-version
          || fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name] 
          && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name].moose-version 
          || 'Moose-latest' }}
