name: Debug Expression

on:
  workflow_call:
    inputs: 
      pharo-versions:
        required: false
        type: string
      image-name:
        required: false
        type: string
      pre-upload-script:
        required: false
        type: string
      create-artifact:
        required: false
        type: boolean
      run-coverage:
        required: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      pharo-versions: ${{ env.pharo-versions }}
    env: 
      pharo-versions: >-
        ${{ inputs.pharo-versions
        || fromJSON(vars.MOOSE_PHARO_VERSIONS)[vars.BRANCHES_CONFIGURATION
        && fromJSON(vars.BRANCHES_CONFIGURATION)[github.base_ref]
        && fromJSON(vars.BRANCHES_CONFIGURATION)[github.base_ref].moose-version
        || fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name]
        && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name].moose-version
        || 'Moose-latest'] }}
    steps:
      - run: echo ${{ env.pharo-versions }}

  print:
    runs-on: ubuntu-latest
    needs: run
    steps:
      - run: echo ${{ needs.run.outputs.pharo-versions }}
