name: Run tests

on:
  workflow_dispatch
        
jobs:
  parameters:
    name: Set parameters
    runs-on: ubuntu-latest
    steps:
      - run: echo 'ref_name' ${{ github.ref_name }}
      - run: echo 'ref_name split' ${{ github.ref_name }}.split('/')[-1]
      
