name: Run tests

on: workflow_call

jobs:
  run:
    runs-on: ubuntu-latest
    name: Pharo12
    steps:

# Run tests and coverage
    
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Option fetching all commits
      - name: Set-up smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Pharo64-12
      - name: Run tests
        run: smalltalkci -s Pharo64-12
        shell: bash
        timeout-minutes: 15
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Upload image as artifact
        
      - name: Build artifact
        run: |
          echo 120 > pharo.version
          mv $SMALLTALK_CI_BUILD/* .
          ls
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: Artifact
          path: |
            *.image
            *.changes
            pharo.version
