name: Run tests

on:
  workflow_call:
    inputs: 
      pharo-versions:
        required: false
        type: string
      pre-upload-script:
        required: false
        type: string
      create-artifact:
        required: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: ${{ fromJSON(vars.MOOSE_PHARO_VERSIONS)['Moose-latest']) }}
    name: ${{ matrix.smalltalk }}
    steps:

# Run tests and coverage
    
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Option fetching all commits
      - name: Set-up smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set image name
        run: |
           echo IMAGE_NAME=${{ env.common-image-name }}-${{ matrix.smalltalk }} >> $GITHUB_ENV
        env: 
          common-image-name: ${{ format('{0}-{1}', github.event.repository.name, github.ref_name) }}

# Upload image as artifact
        
      - name: Build artifact
        if: ${{ inputs.create-artifact }}
        env:
          DEFAULT_IMAGE_NAME: TravisCI # Image name set by smalltalkCI
        run: |
          mv $SMALLTALK_CI_BUILD/* .
          mv $DEFAULT_IMAGE_NAME.image $IMAGE_NAME.image
          mv $DEFAULT_IMAGE_NAME.changes $IMAGE_NAME.changes
          echo ${{ matrix.smalltalk }} | sed -e 's/.*\-//g ; s/\..*//g ; s/$/0/' > pharo.version
        # This pattern transforms as follow: 'Pharo64-9.0' --> '90' and 'Pharo64-10' --> '100'.
        # Remove every character before '-' ; Remove point and anything after it ; add a '0'.

      - name: Upload artifact
        if: ${{ inputs.create-artifact }}
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.IMAGE_NAME }}
          path: |
            ${{ env.IMAGE_NAME }}.image
            ${{ env.IMAGE_NAME }}.changes
            pharo.version
