name: Run tests

on:
  workflow_call:
    inputs: 
      pharo-versions:
        required: false
        type: string
      image-name:
        required: false
        type: string
      pre-upload-script:
        required: false
        type: string
      create-artifact:
        required: false
        type: boolean
      run-coverage:
        required: false
        type: boolean
env:
  branch-name: ${{ (github.event_name == 'push' && github.ref_name)
    || (github.event_name == 'pull_request' && github.base_ref)
    || (github.event_name == 'release' && github.github.event.release.target_commitish) }}
          
jobs:
  parameters:
    name: Set parameters
    runs-on: ubuntu-latest
    outputs:
      pharo-versions: ${{ steps.pharo-version.outputs.pharo-versions }}
    steps:
      - name: Set Pharo versions
        id: pharo-version
        run: >-
          echo pharo-versions=${{ inputs.pharo-versions 
          || (vars.BRANCHES_CONFIGURATION && fromJSON(vars.MOOSE_PHARO_VERSIONS)[fromJSON(vars.BRANCHES_CONFIGURATION)[env.branch-name].moose-version])
          || fromJSON(vars.MOOSE_PHARO_VERSIONS)['Moose-latest'] }} 
          >> $GITHUB_OUTPUT

  debug: 
    runs-on: ubuntu-latest
    needs: parameters
    steps:
        - run: echo ${{ needs.parameters.outputs.pharo-versions }}
      
  run:
    runs-on: ubuntu-latest
    needs: parameters
    strategy:
      fail-fast: false
      matrix:
        smalltalk: ${{ fromJSON(needs.parameters.outputs.pharo-versions) }}
    
    name: ${{ matrix.smalltalk }}
    steps:
      - run: echo ${{ matrix.smalltalk }}

