name: Run tests

on:
  workflow_call:
    inputs: 
      create-artifact:
        required: false
        type: boolean

jobs:
  run:
    runs-on: ubuntu-latest
    name: Pharo12-64
    env:
      IMAGE_NAME: TestingWorkflows-main-Pharo12-64
    steps:

# Run tests and coverage
    
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Option fetching all commits
      - name: Set-up smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Pharo12-64
      - name: Run tests
        run: smalltalkci -s Pharo12-64
        shell: bash
        timeout-minutes: 15
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Upload image as artifact
        
      - name: Build artifact
        if: ${{ inputs.create-artifact }}
        env:
          DEFAULT_IMAGE_NAME: TravisCI # Image name set by smalltalkCI
        run: |
          mv $SMALLTALK_CI_BUILD/* .
          mv $DEFAULT_IMAGE_NAME.image $IMAGE_NAME.image
          mv $DEFAULT_IMAGE_NAME.changes $IMAGE_NAME.changes
          echo 120 > pharo.version

      - name: Upload artifact
        if: ${{ inputs.create-artifact }}
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.IMAGE_NAME }}
          path: |
            ${{ env.IMAGE_NAME }}.image
            ${{ env.IMAGE_NAME }}.changes
            pharo.version
