name: Simple workflow
run-name: >-
  ${{ vars.BRANCHES_CONFIGURATION
  && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name] 
  && fromJSON(vars.BRANCHES_CONFIGURATION)[github.ref_name].run-name 
  || github.ref_name }}

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    name: Pharo 12
    env:
      pharo_image: Pharo64-12 
    steps:    
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set-up smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ env.pharo_image }}
      - name: Run tests
        run: smalltalkci -s ${{ env.pharo_image }}
        shell: bash
        timeout-minutes: 15
      - name: Print playground after run
        run: $SMALLTALK_CI_VM  $SMALLTALK_CI_IMAGE eval "Smalltalk tools workspace name"
      - name: Build artifact
        run: |
          mv $SMALLTALK_CI_BUILD/* .
          echo 120 > pharo.version
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: ${{ env.pharo_image }}
          path: |
            *.image
            *.changes
            *.sources
            pharo.version
      - name: Playground name at the end
        run: ./vm ./*.image eval "Smalltalk tools workspace name" 
