name: RunFrom fork

on:
  push:
  pull_request:
  release:
    types: [ created, edited ]
  workflow_dispatch:
  schedule:
    - cron:  '42 14 23 7 *'

jobs:
  run:
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    secrets: inherit
